Resolve report merge failures updated workflow

diff --git a/.github/workflows/ci-frontend-e2e.yml b/.github/workflows/ci-frontend-e2e.yml
--- a/.github/workflows/ci-frontend-e2e.yml
+++ b/.github/workflows/ci-frontend-e2e.yml
@@ -78,7 +78,9 @@ jobs:
           CI: true
           PLAYWRIGHT_TARGET_ENV: local
         run: |
-          npx playwright test --config ./tests/playwright.config.ts tests/e2e/apply/happy-path-apply-req-form-workflow.spec.ts
+          npx playwright test --config ./tests/playwright.config.ts \
+          tests/e2e/apply/happy-path-apply-req-form-workflow.spec.ts \
+          --reporter=list,blob
 
       - name: Debug logging on failure
         if: failure()
@@ -104,7 +106,7 @@ jobs:
       - name: Verify Blob Report Directory
         run: |
           echo "Contents of blob-report directory:"
-          ls -R blob-report || echo "blob-report directory not found"
+          ls -R /home/runner/work/simpler-grants-gov/simpler-grants-gov/frontend/blob-report || echo "blob-report directory not found"
 
       - name: Upload Blob Report
         if: always()
@@ -138,22 +140,22 @@ jobs:
       - name: Download All Blob Reports
         uses: actions/download-artifact@v4
         with:
-          path: frontend/all-blob-reports
-          pattern: blob-report-shard-*
+          path: /home/runner/work/simpler-grants-gov/simpler-grants-gov/frontend/blob-report
+          pattern: blob-report
           merge-multiple: true
 
       - name: Verify Downloaded Artifacts
         run: |
           echo "Contents of all-blob-reports after download:"
-          ls -R all-blob-reports*
+           ls -R /home/runner/work/simpler-grants-gov/simpler-grants-gov/frontend/blob-report || echo "blob-report directory not found"
 
       - name: Merge Blob Reports into HTML
-        run: npx playwright merge-reports --reporter html ./all-blob-reports
+        run: npx playwright merge-reports --reporter html /home/runner/work/simpler-grants-gov/simpler-grants-gov/frontend/blob-report
 
       - name: Verify merged HTML report
         run: |
           echo "Contents of the merged Playwright HTML report:"
-          ls -R playwright*
+          ls -R playwright* || echo "No merged report found"
 
       - name: Upload Merged HTML Report
         uses: actions/upload-artifact@v4
