Sync ci-frontend-e2e workflow with main

diff --git a/.github/workflows/ci-frontend-e2e.yml b/.github/workflows/ci-frontend-e2e.yml
--- a/.github/workflows/ci-frontend-e2e.yml
+++ b/.github/workflows/ci-frontend-e2e.yml
@@ -26,7 +26,11 @@ jobs:
     name: Run Local E2E Tests
     runs-on: ubuntu-22.04
 
-    # Remove sharding, run only the specified test file
+    strategy:
+      fail-fast: true
+      matrix:
+        shard: [1, 2, 3, 4]
+        total_shards: [4]
 
     steps:
       - name: Checkout repository
@@ -73,14 +77,13 @@ jobs:
           sed -i 's|^SENDY_API_URL=.*|SENDY_API_URL=http://127.0.0.1:3000|' .env.local
           npm run build -- --no-lint
 
-      - name: Run only happy-path-application-submission.spec.ts
+      - name: Run e2e tests (Shard ${{ matrix.shard }}/${{ matrix.total_shards }})
         env:
           CI: true
-          PLAYWRIGHT_TARGET_ENV: local
+          TOTAL_SHARDS: ${{ matrix.total_shards }}
+          CURRENT_SHARD: ${{ matrix.shard }}
         run: |
-          npx playwright test --config ./tests/playwright.config.ts \
-          tests/e2e/apply/happy-path-application-submission.spec.ts \
-          --reporter=list,blob
+          npm run test:e2e
 
       - name: Debug logging on failure
         if: failure()
@@ -106,13 +109,13 @@ jobs:
       - name: Verify Blob Report Directory
         run: |
           echo "Contents of blob-report directory:"
-          ls -R /home/runner/work/simpler-grants-gov/simpler-grants-gov/frontend/blob-report || echo "blob-report directory not found"
+          ls -R blob-report || echo "blob-report directory not found"
 
       - name: Upload Blob Report
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: blob-report
+          name: blob-report-shard-${{ matrix.shard }}
           path: /home/runner/work/simpler-grants-gov/simpler-grants-gov/frontend/blob-report
           retention-days: 1
 
@@ -140,22 +143,22 @@ jobs:
       - name: Download All Blob Reports
         uses: actions/download-artifact@v4
         with:
-          path: /home/runner/work/simpler-grants-gov/simpler-grants-gov/frontend/blob-report
-          pattern: blob-report
+          path: frontend/all-blob-reports
+          pattern: blob-report-shard-*
           merge-multiple: true
 
       - name: Verify Downloaded Artifacts
         run: |
           echo "Contents of all-blob-reports after download:"
-           ls -R /home/runner/work/simpler-grants-gov/simpler-grants-gov/frontend/blob-report || echo "blob-report directory not found"
+          ls -R all-blob-reports*
 
       - name: Merge Blob Reports into HTML
-        run: npx playwright merge-reports --reporter html /home/runner/work/simpler-grants-gov/simpler-grants-gov/frontend/blob-report
+        run: npx playwright merge-reports --reporter html ./all-blob-reports
 
       - name: Verify merged HTML report
         run: |
           echo "Contents of the merged Playwright HTML report:"
-          ls -R playwright* || echo "No merged report found"
+          ls -R playwright*
 
       - name: Upload Merged HTML Report
         uses: actions/upload-artifact@v4
